day1={
    "book ":"予約する",    
    "charge ":"請求する、非難する",
    "allow ":"許す、可能にする",
    "contact ":"連絡を取る　　名：連絡を取る、問い合わせ先",
    "face ":"面する、直面する",
    "hire ":"雇用する、採用する",
    "intend ":"～するつもりである、～を意図する",
    "invite ":"招待する、招く",
    "lie ":"置かれている、ある、横になる",
    "ship ":"発送する、運送する",
    "admit ":"認める、入ることを認める",
    "delay ":"遅らせる、延期する　　遅れる、遅れ",
    "hold ":"持っている、保持する、開催する",
    "offer ":"提供する、示す",
    "run ":"経営する、運営する、走る",
    "wear ":"着ている、身につけている",
    "fix ":"貼り付ける、修理する",
    "apply ":"応募する、申し込む　適用する",
    "gather ":"集める　集まる",
    "fit ":"ぴったり合う、備え付ける",
    "attend ":"出席する、通う",
    "cancel ":"取り消す、キャンセルする",
    "add ":"付け加える、加算する",
    "elect ":"選出する",
    "work ":"作動する、働く",
    "agree ":"同意する",
    "expect ":"予想する、期待する",
    "reach ":"達する、～に手を伸ばしてとる、手を伸ばす",
    "serve ":"提供する、勤務する",
    "earn ":"稼ぐ、収益を上げる",
    "cost ":"（費用）かかる、必要とする",
    "save ":"節約する、貯める、救う",
    "spend ":"（金・時間）費やす、使う",
    "adopt ":"採用する",
    "lack ":"～を欠く、不足する　　不足",
    "miss ":"逃す、～がいなくて残念に思う",
    "own ":"所有する　自分自身の、特有の",
    "worry ":"心配する、心配させる　　心配事",
    "lead ":"指導する、先導する、～する気にさせる",
    "solve ":"解決する",
    "arrange ":"手配する、整える",
    "connect ":"結びつける、取り次ぐ",
    "announce ":"発表する、告知する",
    "request ":"求める、要請する　　要請",
    "decline ":"断る、却下する　　低下する、下落する",
    "explain ":"説明する",
    "inform ":"知らせる、伝える",
    "express ":"表現する、示す",
    "introduce ":"紹介する、導入する",
    "receive ":"受け取る、受ける",
    "consider ":"考える、配慮する",
    "develop ":"発展させる、開発する　　発展する、伸展する",
    "prepare ":"準備をさせる、用意する",
    "compare ":"比較する",
    "display ":"展示する、示す　　展示品",
    "remain ":"～のままである、残っている",
    "create ":"想像する、創出する",
    "divide ":"分割する、割り算する　　分割、ギャップ",
    "issue ":"発行する　　発行、号、問題点",
    "process ":"処理する、加工する　　過程、経過",
}
day2={
    "ready":"準備ができた",
    "proud ":"誇りに思う",
    "serious ":"重大な、真剣な",
    "curious ":"興味がある、好奇心が強い",
    "annual ":"年一回の、毎年の、1年間の",
    "crawded ":"混みあった、ぎっしり詰まった",
    "local ":"地元の、国内の、各駅停車の",
    "past ":"過去の、先の",
    "urgent ":"緊急の、急を要する",
    "senior ":"地位が上の、年長の",
    "polite ":"丁寧な、洗礼された",
    "formal ":"正式な",
    "corporate ":"会社の、法人の",
    "former ":"前の、先の",
    "previous ":"前の、先の",
    "available ":"利用可能な、空いている",
    "capable ":"～できる、能力にある",
    "ideal ":"理想的な、申し分の",
    "familiar ":"よく知られている、よく知っている",
    "convenient ":"便利な",
    "various ":"さまざまな、多様な",
    "similar ":"似通った",
    "whole ":"全体の、すべての　　全部",
    "further ":"さらなる、それ以上の　　さらに",
    "huge ":"莫大な、巨大な",
    "well-known ":"有名である",
    "unusual ":"異常な、まれな",
    "common ":"普通の、よくある",
    "expensive ":"高価な、費用のかかる",
    "urban ":"都会の、都市の",
    "sincere ":"心よりの、誠実な",
    "confident ":"自信のある",
    "responsible ":"責任がある",
    "thick ":"厚い、濃厚な",
    "original ":"元の、独創的な　　本物",
    "traditional ":"伝統的な，慣習の",
    "rapid ":"急速な、高速の",
    "timely ":"タイミングのいい、迅速な",
    "extra ":"余分の、追加の",
    "tight ":"きつい、厳しい",
    "recently ":"最近",
    "lately ":"最近",
    "mainly ":"主として",
    "particularly ":"特に、とりわけ",
    "exactly ":"正確に、まさに",
    "frequently ":"頻繁に、よく",
    "hardly ":"ほとんど～ない",
    "rarely ":"めったにない～",
    "seldom ":"めったに～ない",
    "nearly ":"ほとんど、近く、危うく～するところで",
    "however ":"しかしながら、一方では",
    "threfore ":"それゆえに、だから",
    "regularly ":"定期的に、規則正しく",
    "certainly ":"確かに、本当に",
    "likely ":"おそらく　　ありそうな",
    "probably ":"おそらく",
    "overtime ":"時間外で、時間外の",
    "overseas ":"海外に、海外の",
    "fairly ":"かなり、公正に",
    "quickly ":"すぐに、すばやく",
}
day3={
    "firm ":"会社　　固い、強固な",
    "deal ":"取引、契約",
    "trade ":"取引、貿易　　取引する",
    "date ":"日付、日取り、会う約束",
    "decade ":"１０年",
    "rate ":"料金、比率、速度　　評価する",
    "fee ":"料金、費用",
    "share ":"割り当て、占有率、株式　　共有する",
    "effort ":"努力、苦労",
    "trust ":"信用、信頼",
    "line ":"ランイナップ、列、線",
    "item ":"品目、項目",
    "goods ":"商品、製品",
    "unit ":"単位、装置",
    "fair ":"見本市、フェア",
    "rest ":"休息、休み、残り",
    "leave ":"休暇、～を去る、任せる",
    "fun ":"楽しみ、愉快",
    "period ":"期間",
    "form ":"書式，形態",
    "skill ":"技能、技量",
    "ability ":"能力、才能",
    "duty ":"業務、義務、関税",
    "shift ":"交換勤務の仕事、変動、変える",
    "benefit ":"利益、給付、特典",
    "package ":"小包、パッケージ",
    "role ":"役割、機能",
    "facility ":"設備、施設、手段",
    "industry ":"産業、工場",
    "notice ":"告知、掲示、注意　　気づく",
    "author ":"著者、作家",
    "ceremony ":"式典、セレモニー",
    "audience ":"慣習、観客、視聴者",
    "lecture ":"講習、講義",
    "subject ":"話題、テーマ",
    "budget ":"予算、安い",
    "fund ":"資金、基金",
    "figure ":"数字、図表、人物",
    "damage ":"損害、被害　損害を与える",
    "interest ":"関心、利点、金利",
    "appointment ":"約束、アポイント、任命",
    "relation ":"関係",
    "attention ":"注意、注目",
    "mind ":"考え、心　　気にする",
    "rumor ":"うわさ",
    "example ":"例、手本",
    "matter ":"事柄、事案　　重要である",
    "content ":"内容、中身",
    "district ":"地区、区域",
    "room ":"余地、部屋",
    "condition ":"条件、状態",
    "effect ":"影響、効果",
    "factor ":"要因、要素",
    "policy ":"政策、保険書",
    "reason ":"理由、根拠　　推論する",
    "value ":"価値、有用性　　評価する",
    "result ":"結果、結末",
    "demand ":"需要、要求",
    "fault ":"欠陥、過失",
    "article ":"記事、条項",
}
day4={
    "order ":"注文、命令、順番、秩序",
    "retail ":"小売り、小売りの",
    "profit ":"利益",
    "billing ":"請求",
    "rent ":"賃貸料、貸す、借りる",
    "career ":"職業、仕事",
    "employee ":"社員、被雇用者",
    "management ":"経営、管理",
    "excutive ":"経営幹部、経営陣の",
    "department ":"部門",
    "position ":"役職、仕事、位置",
    "interview ":"面接、インタビュー、面接する",
    "background ":"経歴、背景",
    "graduate ":"卒業生、卒業する",
    "profession ":"職業、専門職",
    "labor ":"労働",
    "recruit ":"新入社員、　　募集する",
    "lawyer ":"弁護士、法律家",
    "contract ":"契約",
    "crew ":"（特殊技能の）チーム、（飛行機などの）乗務員",
    "revenue ":"収入、収益",
    "income ":"収入、所得",
    "expense ":"費用、経費",
    "capital ":"資本、大文字、首都",
    "stock ":"在庫、株式",
    "return ":"返品する　　返品",
    "receipt ":"領収書、レシート、受領",
    "branch ":"支社、支店、枝",
    "cafeteria ":"社員食堂",
    "committee ":"委員会",
    "campaign ":"宣伝活動、キャンペーン",
    "agency ":"代理店、機関",
    "consumer ":"消費者",
    "device ":"装置、機器",
    "equipment ":"装置、機器",
    "machinery ":"（おおきい）機械類，（組織）機構",
    "supply ":"供給、用品",
    "finding ":"調査結果、報告、所見",
    "agriculture ":"農業",
    "security ":"安全、警備、有価証券",
    "broad ":"搭乗する",
    "luggage ":"荷物、旅行用カバン",
    "departure ":"出発",
    "passenger ":"乗客",
    "tour ":"ツアー、見学",
    "sightseeing ":"観光",
    "transportation ":"交通機関、運送",
    "round ":"往復の、丸い　　～を回って",
    "parking ":"駐車、駐車場",
    "change ":"小銭、おつり",
    "clerk ":"事務員、店員",
    "furniture ":"家具",
    "stair ":"階段",
    "parcel ":"小包、荷物",
    "sign ":"標識、前兆　　署名する",
    "cross ":"横切る，渡る",  
    "direction ":"方向、指示",
    "neighborhood ":"近所、隣人",
    "climate ":"気候、雰囲気",
    "temperature ":"気温、体温",
}
day5={
    "as well as":"～と同様に",
    "at east":"気楽に",
    "at first":"最初のうちは",
    "at home":"国内で、自宅で、くつろいだ",
    "at least":"少なくとも",
    "at once":"すぐに",
    "at the same time":"同時に",
    "because of":"～という理由で、～のために",
    "due to":"～が原因で",
    "both A and B":"AとBのどちらも",
    "each other":"お互いに",
    "either A or B":"AかBのどちらか",
    "for a while":"しばらくの間",
    "from now on":"今後は",
    "in charge of":"～を担当して、～を管理して",
    "in fact":"実のところ、それどころか",
    "in fornt of":"～のすぐ前に",
    "in the future":"将来は、これからは",
    "in time for":"～に間に合って",
    "instead of":"～ではなく、～の代わりに",
    "neigther A nor B":"AもBも～ない",
    "next to":"～の隣に、～の次に",
    "no later than":"～までに、～より遅れることなく",
    "no longer":"もはや～ない",
    "not only A but also B":"AばかりでなくBもまた",
    "on duty":"勤務中で",
    "out of order":"故障して、不調で",
    "so far":"これまでのところ",
    "such as":"たとえば～など",
    "under way":"進行中で",
    "be about to do":"まさに～する",
    "be absent from":"～を欠席する、～を休む",
    "be likely to do":"～しそうだ",
    "belong to":"～に属する",
    "call for":"～を求める",
    "carry out":"～を実行する",
    "check out":"チェックアウト、支払いをする",
    "depend on":"～に依存する、～次第だ",
    "feel free to do":"自由に～する、遠慮なく～する",
    "fill out[in]":"～に記入する",
    "foucus on":"～に焦点を当てる",
    "get off":"降りる",
    "go ahead":"先へ進む、進行する",
    "keep up with":"～についていく、～の最新情報に通じている",
    "lay off":"～を解雇する",
    "look forward to":"～を楽しみに待つ",
    "make sure":"確かめる",
    "pick up":"～を取り上げる、～を車で迎える",
    "point out":"～を指摘する",
    "put off":"～を延期する",
    "put on":"～を身に着ける",
    "refer to":"～を参照する、～を言及する",
    "see off":"～を見送る",
    "set up":"～を設定する、～を設置する",
    "take off":"離陸する、軌道に乗る",
    "take place":"開催される、起こる",
    "try on":"～を試着する",
    "turn off":"消す、切る",
    "used to do":"～したものだ",
    "work for":"働く",
}
day6={
    "file":"ファイルする、申請する",
    "attach":"添付する、貼り付ける",
    "last":"続く、持続する",
    "import":"輸入する、輸入",
    "urge":"促す、説得する、衝動",
    "prefer":"～より好む",
    "exchange":"交換する、両替する",
    "caluculate":"計算する、推定する",
    "require":"要求する、～を必要とする",
    "postpone":"延期する、先送りにする",
    "incerase":"増やす、高める",
    "reduce":"減少する",
    "persuade":"説得する、納得させる",
    "tend":"～する傾向がある",
    "fill":"満たす、埋め尽くす",
    "hang":"掛ける",
    "entertain":"楽しませる、接待する",
    "appear":"～のように見える、現れる",
    "confirm":"確認する",
    "remind":"気づかせる、思い出させる",
    "operate":"運営する、操作する",
    "maintain":"整備する、維持する、主張する",
    "improve":"改善する、上達する",
    "extend":"拡大する、延長する",
    "handle":"処理する、対処する、取っ手",
    "accept":"受け取る",
    "reject":"拒否する、不採用にする",
    "consume":"消費する、消耗する",
    "resign":"辞任する、退職する",
    "congratulate":"祝う、祝福する",
    "include":"含む",
    "contain":"含む、抑える",
    "involve":"含む、関わらせる",
    "complain":"文句を言う、不満を言う",
    "apologize":"詫びる",
    "publish":"公にする、出版する",
    "release":"公表する、発売する",
    "seek":"探す",
    "update":"印刷する、最新のものにする、最新情報",
    "provide":"提供する、与える",
    "correct":"訂正する、正しい、ふさわしい",
    "deliver":"届ける",
    "distribute":"配る、流通させる",
    "attract":"引きつける、誘導する",
    "state":"述べる、～と言う",
    "renew":"更新する",
    "deposit":"預金する、預ける",
    "participate":"参加する",
    "host":"主催する、司会をする",
    "concentrate":"集中する、専念する",
    "prevent":"妨げる、防止する",
    "enable":"～することを可能にする",
    "sort":"分類する、整理する、種類",
    "describe":"説明する、描写する",
    "locate":"見つける、位置付ける",
    "treat":"対応する、治療する、おごる",
    "disappoint":"失望させる",
    "suffer":"被る、苦しむ",
    "survive":"生き残る",
    "violate":"違反する、侵害する",
}
day7={
    "eager":"熱心な、～したがって",
    "proper":"適当な、固有の",
    "suitable":"適当な、ふさわしい",
    "punctual":"時間に正確な",
    "positive":"積極的な、好意的な",
    "opposite":"逆の、反対側の",
    "entire":"全体の、全部の",
    "domestic":"国内の、家庭の",
    "broad":"幅の広い、広範囲に及ぶ",
    "extensive":"広い、広範な",
    "obvious":"明らかな",
    "plain":"明白な、平易な、無地の",
    "reasonable":"手ごろな、合理的な",
    "reliable":"信頼できる、頼もしい",
    "stable":"安定した、持続性のある",
    "brief":"簡潔な、短い",
    "complete":"完璧な、徹底した",
    "effective":"有効な、能力のある",
    "efficient":"効率的な、有能な",
    "flexible":"柔軟な、融通の利く",
    "pleasant":"楽しい、快適な",
    "delighted":"喜んでいる",
    "comfortable":"快適な、心地のよい",
    "attractive":"魅力的な、興味をそそる",
    "boring":"うんざりさせる、つまらない",
    "nervouse":"心配して、緊張して",
    "luxurious":"贅沢な、豪華な",
    "valuable":"価値のある、立派な",
    "wealthy":"裕福な、豊富な",
    "significant":"重要な、相当な",
    "informative":"役に立つ",
    "initial":"最初の、初めの",
    "primary":"主要な、初期段階の",
    "complicated":"複雑な、入り組んだ",
    "qualified":"資格のある、能力のある",
    "superior":"優れている、上司",
    "independent":"独立している、無関係の",
    "intelligent":"知性的な、頭がいい",
    "manual":"手を扱う、肉体労働の、取扱説明書",
    "individual":"個人の、個別の",
    "additional":"追加の、さらなる",
    "aware":"意識している、わかっている",
    "strict":"厳格な、厳重な",
    "mutual":"相互の、共通の",
    "precise":"精密な、正確な",
    "net":"正味の、最終的な",
    "ordinary":"普通の、一般的な",
    "secure":"安全な、安定した、確保する",
    "practical":"実際の、現実的な",
    "up-to-date":"最新の、現代的な",
    "moreover":"さらに、そのうえ",
    "otherwise":"そうでないと、それ以外には、別な風に",
    "besides":"さらに、それに、付け加えて",
    "insted":"その代わりに、そうではなく",
    "actually":"本当のところ、実は",
    "unfortunately":"残念ながら、不幸にも",
    "especially":"特に、とりわけ",
    "definitely":"確かに、確実に",
    "gradually":"徐々に、だんだんと",
    "immediately":"ただちに、直接に",
}
day8={
    "attendee":"出席者",
    "conference":"会議、総会",
    "proposal":"提案、企画案、プロポーズ",
    "sector":"業界、部門",
    "negotiation":"交渉",
    "applicant":"応募者、志願者",
    "candidate":"候補者",
    "vote":"投票、投票する",
    "anniversary":"記念日",
    "award":"賞、授与する",
    "balance":"残高、均衡",
    "quarter":"四半期、四分の一",
    "complaint":"苦情、クレーム",
    "respect":"尊敬、事項",
    "influence":"影響を与える、影響",
    "operation":"運営、操作、手術、作戦",
    "performance":"実行、実績、演奏",
    "progress":"進歩、進展",
    "theme":"テーマ、趣旨",
    "view":"意見、眺め",
    "reseach":"研究、調査、　研究調査をする",
    "deadline":"締め切り、納期",
    "material":"素材、原材料",
    "method":"方法、手段",
    "quality":"性質、品質",
    "cooperation":"協力",
    "option":"選択肢",
    "purpose":"目的、用途、趣旨",
    "aim":"目標　狙う",
    "gain":"利益、増加、獲得する",
    "opportunity":"機会",
    "status":"地位、状況",
    "practice":"実践、練習　練習する",
    "conflict":"重複、対立",
    "amount":"量、金額、合計～になる",
    "procedure":"手順、手続き",
    "function":"機能、職務、行事",
    "aspect":"側面、観点",
    "aid":"援助、支援する",
    "emergency":"緊急事態、非常時",
    "honor":"光栄、尊敬",
    "applause":"拍手、賞賛",
    "greeting":"あいさつ",
    "suggestion":"提案、アドバイス",
    "statement":"声明、明細書、申し立て",
    "summary":"要約、概要",
    "property":"財産、不動産",
    "household":"世帯、家族、家庭の",
    "region":"地域、領域",
    "site":"土地、現場",
    "attitude":"態度、心構え",
    "manner":"やり方、礼儀",
    "stuff":"もの、事、食べ物、飲み物",
    "concern":"心配事、関心、関係する",
    "atmosphere":"雰囲気、大気",
    "environment":"環境、周囲の状況",
    "guideline":"指針、ガイドライン",
    "rear":"後ろ、背後",
    "generation":"世代",
    "reminder":"思い出させるもの、確認、督促状",
}
day9={
    "account":"顧客、口座、説明",
    "accountant":"経理、会計士",
    "board of directors":"取締役員",
    "colleague":"同僚",
    "supervisor":"管理者、上司",
    "human resources":"人材、人事部",
    "job vacancy":"求人、ポストの空席",
    "resume":"履歴書",
    "personnel":"人員、人事",
    "retire":"退職する、引退する",
    "handout":"資料、プリント",
    "chart":"図表、グラフ",
    "brochure":"小冊子、案内書",
    "bulletin":"社内報、会報",
    "assembly":"集まり、組み立て",
    "session":"会合、集まり、セッション",
    "chair":"司会をする、議長を進める",
    "presentation":"発表、プレゼン",
    "questionnaire":"アンケート、質問書",
    "respondent":"回答者、応答者",
    "commerce":"取引、貿易",
    "signature":"署名、特色",
    "invest":"投資する",
    "financial":"財務の、金銭的な",
    "paycheck":"給与",
    "debt":"借金、負債",
    "currency":"通貨、流通",
    "exhibition":"展示会",
    "memorandum":"回覧、事務連絡票",
    "reschedule":"（日程を）再調整する、延期する",
    "headquarters":"本社",
    "commute":"通勤する",
    "manufacture":"製造業者、メーカー",
    "construction":"建設",
    "architecture":"建築",
    "laboratory":"研究所、実験室",
    "insurance":"保険",
    "extension":"内線、延長",
    "renovate":"改修する、リフォームする",
    "cargo":"貨物",
    "vehicle":"車両、手段",
    "automobole":"自動車",
    "destination":"目的地", 
    "immigration":"入国検査、入国",
    "souvenir":"お土産",
    "meal":"食事",
    "landscape":"風景、造園する",
    "story":"階",
    "suburb":"郊外",
    "directory":"住所録、案内",
    "utensil":"台所用品",
    "kitchenware":"台所用品",
    "dine":"食事をする",
    "grocery":"日用雑貨、食料品",
    "dairy":"乳製品、酪農場",
    "garbage":"生ごみ",
    "medication":"薬",
    "pack":"詰める、荷造りする",
    "pour":"注ぐ、（雨が）激しく降る",
    "broadcast":"番組、放送する",
}
day10={
    "by the way":"ところで",
    "for instance":"たとえば",
    "based on":"～に基づいて",
    "accordng to":"～によると、～に応じて",
    "after all":"結局のところ、何と言っても",
    "as a result":"結果として",
    "as far as ～ concerned":"～に関するかぎり",
    "as far":"～について、～に関して",
    "behind scedule":"予定より遅れて",
    "by accident":"偶然に",
    "except for":"～を除いて",
    "far from":"～にほど遠い、決して～でない",
    "free of charge":"無料で",
    "in addition to":"～に加えて",
    "in brief":"簡潔に、端的に言って",
    "in favor of":"～を支持して、～を好んで",
    "in spite of":"～にもかかわらず",
    "now that":"～なので",
    "on behalf of":"～を代表して、～のために",
    "on top of":"～の上に、～に加えて",
    "right away":"すぐに",
    "side by side":"並んで",
    "thanks to":"～のおかげで、～のせいで",
    "up to":"～の義務で、～次第で、～に至るまで",
    "in case":"万一～するといけないので、もし～の場合には",
    "so that ～ can":"～するために、～できるように",
    "even if":"たとえ～でも",
    "along with":"～と一緒に",
    "on the other hand":"他方では、別の見方では",
    "owing to":"～の理由で、～のために",
    "be anxious to do":"～することを切望する",
    "be engaged in":"～に従事している",
    "be supposed to do":"～することになっている",
    "call in sick":"病欠の電話をする",
    "catch up with":"～に追いつく",
    "deal with":"～に対処する、～を取り扱う",
    "dispose of":"～を処分する、～を廃棄する",
    "do a favor":"手を貸す、役立つ",
    "feel like ～ing":"～したい",
    "get back to":"～に折り返しの連絡をする",
    "get rid of":"～を取り除く、～を廃棄する",
    "get together":"集まる、待ち合わせる",
    "go over":"～を調べる、～を検討する、～を超える",
    "hand in":"～を提出する、～を手渡す",
    "hang up":"切る、～を中断する",
    "happen to do":"たまたま～する",
    "help onself to":"自由に～をとって食べる・飲む",
    "major in":"～を専攻する",
    "manage to do":"何とか～する",
    "pay attention to":"～に注意する、～に気を配る",
    "pay off":"報われる、完結する",
    "put up with":"～に我慢する、～に耐える",
    "range from A to B":"AからBに及ぶ",
    "show up":"現れる",
    "shut down":"～を中断する、～を停止する",
    "sign up for":"～に登録する、～に申し込む",
    "start with":"～から始める",
    "step down":"辞任する、引退する",
    "take it easy":"くつろぐ",
    "take part in":"～に参加する",
}
day11={
    "launch":"発売する、始める、発射する",
    "achieve":"達成する、獲得する",
    "inquire":"問い合わせる、調査する、たずねる",
    "examine":"調べる、検討する",
    "donate":"寄付する",
    "contribute":"貢献する、寄付する",
    "assign":"割り当てる、任命する",
    "designate":"指名する、指定する",
    "recommend":"勧める、推薦する",
    "submit":"提出する",
    "afford":"余裕がある",
    "celebrate":"祝う",
    "demonstrate":"実演して説明する",
    "approve":"承認する",
    "encourage":"励ます、勧める",
    "gurantee":"保証する",
    "insist":"強く主張する、断言する",
    "claim":"主張する、要求する",
    "obtain":"手に入れる",
    "acquire":"獲得する、身に着ける",
    "promote":"昇格させる、販売促進する",
    "lean":"寄りかかる、身を乗り出す",
    "raise":"引き上げる、提起する",
    "load":"積み込む",
    "permit":"許可する",
    "install":"設置する、インストールする",
    "subcribe":"購読する、加入する",
    "post":"発表する、投稿する",
    "insert":"挿入する、投入する",
    "adjust":"調整する、適応する",
    "appreciate":"評価する、感謝する",
    "recognize":"認識する、評価する",
    "collaborate":"共同作業を行う",
    "observe":"気づく、守る、観察する、祝う",
    "consult":"相談する、診てもらう、調べる",
    "protect":"保護する、させないようにする",
    "purchase":"購入する",
    "expand":"拡大する、進出する",
    "realize":"理解する、実現する",
    "enclose":"同封する",
}
day12={
    "conduct":"実施する、案内する、指揮する",
    "undergo":"経験する、受ける",
    "inspect":"詳しく調べる、視察する",
    "predict":"予想する、予報する",
    "expire":"期限が切れる、失効する",
    "reflect":"反映する、熟考する",
    "cater":"調達する、応じる",
    "replace":"取り替える、引き継ぐ",
    "withdraw":"引き出す、撤回する、撤退する",
    "transfar":"移転する、送金する、移転する",
    "conclude":"結論出す、終える",
    "detarmine":"決定する",
    "restrict":"制約する、制限する",
    "emphasize":"強調する、制限する ",
    "evaluate":"評価する、査定する",
    "regard":"評価する、～とみなす",
    "investigate":"調査する，捜査する",
    "outline":"要点を述べる、概説、輪郭",
    "indicate":"指摘する、示す",
    "register":"登録する、書留にする",
    "avoid":"避ける",
    "hesitate":"ためらう、躊躇する",
    "neglect":"怠る、無視する",
    "confuse":"困惑する、混同する",
    "prohibit":"禁止する、妨げる",
    "suspend":"中止する、停止する",
    "refrain":"控える、慎む",
    "interrupt":"さえぎる、邪魔をする",
    "revise":"改訂する、改変する",
    "modify":"変更する、修正する",
    "address":"取り組む、話しかける",
    "ensure":"確実にする、保証する",
    "implement":"実施する、履行する、道具、用具",
    "authorize":"認める、権限を与える",
    "establish":"設立する、確立する",
    "accommodate":"収容する、便乗を図る",
    "analyze":"分析する",
    "relocate":"移転する、転勤する",
    "remove":"取り除く",
    "recover":"取り戻す、回復する",
}
day13={
    "due":"支払期間が来て、～がする予定で",
    "valid":"有効な、妥当な",
    "economical":"節約する、割安の",
    "fiscal":"財務の、会計の",
    "accurate":"正確な、精密な",
    "patient":"我慢強い、寛容な、患者",
    "specific":"特定の、具体的な",
    "upcoming":"近く起こる",
    "intensive":"集中的な、徹底的な",
    "diverse":"さまざまな、多様な",
    "compentent":"有能な、適任の",
    "proficient":"習熟した、技量のある",
    "competitive":"競争力のある、競争が激しい",
    "dedicated":"献身的な、一生懸命な",
    "industrious":"勤勉な",
    "innovative":"革新的な、独創的な",
    "modest":"謙虚な、控えめの",
    "vacant":"空いている、欠員の",
    "permanent":"永遠の、正社員の",
    "temporary":"一時的な、臨時の",
    "consecutive":"連続した",
    "substantial":"相当な、実質上な",
    "sufficient":"十分な、足りる",
    "numerous":"たくさんの、多数の",
    "multiple":"多数の、多重の",
    "respective":"それぞれの、各自の",
    "remarkable":"顕著な。際立った",
    "outstanding":"傑出する、注目すべき、未払いの",
    "durable":"耐久性に優れた、丈夫な",
    "exclusive":"独占的な、高級な",
    "alternative":"別の、型にはまらない",
    "current":"現在の、流通，動向",
    "liable":"～に責任がある、～しがちである",
    "potential":"可能性、見込みのある、潜在性",
    "lucrative":"儲かる、収益をもたらす",
    "prosperous":"繁栄する、成功している",
    "precious":"貴重な、高価な",
    "sustainable":"持続可能な",
    "voluntary":"自発的な、自主参加の",
    "typical":"典型的な",
}
day14={
    "acclaimed":"賞賛を受けている、高名な",
    "ambitious":"野心のある、～を熱望する",
    "cordial":"心のこもった",
    "mature":"成熟した、満期の",
    "prestigious":"一流の、権威のある",
    "unanimous":"満場一致の",
    "remote":"遠く離れた、わずかな",
    "adjacent":"隣接する",
    "comprehensive":"包括的な、広範な",
    "administrative":"経営の",
    "complimentary":"無料で提供される",
    "mandatory":"強制的な、必須の",
    "preliminary":"予備的な、準備の",
    "relevant":"関連がある、適切な",
    "feasible":"実現可能な、見込みのある",
    "authentic":"本物の、信頼できる",
    "confidential":"精密の、内密の",
    "crucial":"きわめて重要な",
    "generous":"気前のいい、寛大な",
    "inevitable":"避けられない",
    "considerably":"かなり、相当",
    "approximately":"おおよそ、約",
    "tentatively":"仮に、暫定的に",
    "mostly":"たいてい、大部分は",
    "eventually":"最後には、結局は",
    "regrettably":"残念ながら",
    "extremely":"きわめて、極端に",
    "relatively":"割合に、比較的に",
    "separately":"別々に",
    "thoroughly":"完全に、入念に",
    "furthermore":"さらに、しかも",
    "meanwhile":"その間に、一方では",
    "subsequently":"その次に、その後",
    "afterward":"後で、その後",
    "simultaneously":"同時に",
    "consequently":"結果として、したがって",
    "accordingly":"それにしたがって、それを受けて",
    "presumably":"おそらく",
    "apparently":"外見上は、どうやら",
    "merely":"単に、ただ",
}
day15={
    "agenda":"課題、予定表",
    "costom":"習慣、税関",
    "draft":"下書き、原稿",
    "input":"意見、協力、入力",
    "refund":"返金",
    "asscoiate":"仲間、同僚",
    "review":"調査、評価",
    "survey":"調査、アンケート",
    "feedback":"反応、意見、フィードバック",
    "occasion":"行事、祭典",
    "expertise":"専門知識",
    "biography":"伝記、経歴",
    "gratitude":"感謝",
    "instruction":"指示、説明書",
    "loyalty":"忠実、支持",
    "objective":"目標、客観的な",
    "phase":"段階、局面",
    "prospect":"将来見通し、将来性のある",
    "strategy":"戦略",
    "venture":"事業、冒険",
    "experiment":"実験、試み",
    "appliance":"家電製品、器具",
    "resource":"資源、資産",
    "output":"生産高、出力",
    "instrument":"器具、楽器、手段",
    "flaw":"欠陥、不備",
    "circumstance":"状況、環境",
    "situation":"状況、事情",
    "breakthrough":"秘術革新、飛躍的な進歩",
    "timeline":"スケジュール、年表",
    "degree":"学位、程度、度",
    "incentive":"優遇措置、奨学金",
    "reference":"推薦、参照",
    "privilege":"特典、特権を与える",
    "commission":"歩合給、報酬、委員会",
    "certificate":"証明書、証人",
    "hierarchy":"階層、ヒエラルキー",
    "routine":"日課、習慣",
    "pastime":"娯楽、気晴らし",
    "well-being":"快適さ、幸福",
}
day16={
    "hospitality":"もてなし、接客",
    "amenity":"生活を便利にする施設",
    "fare":"料理、運賃、娯楽作品",
    "flavor":"味、雰囲気",
    "appetite":"食欲、欲求",
    "admission":"入場料、入会",
    "duration":"継続時間、有効期間",
    "venue":"開催場所",
    "premise":"建物の敷地",
    "podium":"演壇",
    "celebrity":"有名人、セレブ",
    "legend":"伝説、達成者、凡例",
    "integrity":"忠実、完全な状態",
    "behavior":"振る舞い、行動",
    "heritage":"遺産、継承物",
    "reputation":"評判、名声",
    "token":"しるし、象徴",
    "tip":"助言、チップ、先端",
    "measure":"手段、対策、基準、測る",
    "remark":"意見、発言、助言",
    "alliance":"提携",
    "commitment":"約束、取り組み",
    "compromise":"妥協する",
    "counterpart":"相手側",
    "predecessor":"前任者、前のもの",
    "outlook":"展望、予想、眺め",
    "prespective":"展望、全体像",
    "outcome":"結果、成果",
    "advantage":"優位、利点",
    "impact":"影響、衝撃",
    "portion":"部分、一部",
    "element":"要素、成分",
    "coverage":"報道範囲、適用範囲",
    "excerpt":"抜粋する",
    "principle":"原則、主義",
    "institution":"団体、機関、制度",
    "structure":"建造物,構造",
    "regulation":"原則、規則",
    "alert":"警告",
    "row":"列、並び",
}
day17={
    "estimate":"見積もり",
    "invoice":"請求書",
    "installment":"分割払い",
    "inventory":"在庫",
    "storage":"保管、収納",
    "warehouse":"倉庫",
    "courier":"宅配便",
    "crate":"運送用の箱、枠箱",
    "found":"設立する、建設する",
    "enterprise":"事業、会社",
    "representative":"担当者、代表者",
    "janitor":"清掃係、用務員",
    "mechanic":"機械工、修理工",
    "plumber":"配管工",
    "receptionist":"受付係",
    "assignment":"事務、割り当て",
    "chore":"雑務、決まった仕事",
    "outsource":"外部委託する",
    "subordinate":"部下",
    "subsidiary":"子会社",
    "merchandise":"商品、販売促進する",
    "outlet":"小売店、コンセント、排水溝",
    "patronage":"愛顧、ひいき",
    "prototype":"試作品",
    "component":"部品、成分",
    "specification":"仕様、明細",
    "procurement":"調達、入手",
    "gadget":"小型機器",
    "pharmaceutical":"医薬品の、製薬会社",
    "patent":"特許",
    "reimburse":"払戻す、返済する",
    "audit":"監査、会計検査",
    "bankrupt":"破産した、倒産した",
    "merger":"合併",
    "statistic":"統計数字",
    "term":"条件、任期、専門用語",
    "warranty":"保証",
    "transaction":"取引、処理",
    "bid":"入札する",
    "mortgage":"住宅ローン、担保",
}
day18={
    "convence":"開催する、招集する",
    "minutes":"議事録",
    "attire":"服装",
    "banquet":"宴会",
    "proofread":"校正する",
    "manuscript":"原稿",
    "periodical":"雑誌、定期的な",
    "refreshment":"軽食",
    "credential":"実績、証明書",
    "pave":"舗装する",
    "itinerary":"旅程表、スケジュール",
    "excursion":"遠足、小旅行",
    "landmark":"名所、目印",
    "beverage":"飲み物",
    "cuisine":"料理",
    "ingredient":"材料、要素",
    "personal belongings":"所持品",
    "inclement":"悪天候の、荒れ模様の",
    "meteorologist":"気象予報士、気象学者",
    "precipitation":"降水",
    "spectator":"観衆、観客",
    "jam":"渋滞、詰まる、群がる",
    "pedestrian":"歩行者",
    "auditorium":"公会堂、講堂",
    "usher":"案内する、案内係",
    "stack":"積み上げる、積み重ね",
    "stationery":"文房具、便せん",
    "sweep":"掃除する、掃く",
    "waste":"廃棄物、ごみ、浪費",
    "utility":"公共料金、公共施設",
    "detergent":"洗剤",
    "laundry":"洗濯",
    "fabric":"繊維、布地",
    "scholarship":"奨学金",
    "tuition":"授業料、資金",
    "enroll":"登録する、入学する",
    "browse":"見て回る、閲覧する",
    "masterpiece":"傑作",
    "residence":"住宅、住居",
    "symptom":"症状、兆候",
}
day19={
    "a host of":"数多くの～",
    "a range of":"さまざまな～、広範囲の～",
    "ahead of":"～より早く、～の前に",
    "apart from":"～はともかく、～を除いて、～から離れて",
    "around the clock":"24時間、一日中",
    "as a matter of fact":"実のところ",
    "as a whole":"全体として",
    "as of":"～付きで、～時点で",
    "at hand":"すぐそこに、近くに",
    "at one's convenience":"都合のいいように",
    "at the moment":"今のところ",
    "by way of":"～を経由して",
    "every other":"ひとつおきの、他のすべて",
    "for the time being":"当分の間、さしあたりは",
    "in a row":"連続して、1列になって",
    "in connection with":"～に関連して",
    "in contrast to":"～と対照的に",
    "in effect":"事実上は、発効して",
    "in general":"一般的に、たいていは",
    "in good shape":"体調がいい、健全な状態で",
    "in honor of":"～に敬意を表して、～を祝して",
    "in light of":"～を考慮して",
    "in place of":"～の代わりに",
    "in search of":"～を探して、～を求めて",
    "in terms of":"～の点では",
    "in the long run":"長い目で見れば、長期的には",
    "in the meantime":"その間に、そうこうしているうちに",
    "in turn":"順番に、今度は",
    "on account of":"～が理由で、～のために",
    "on the contrary":"それどころか、むしろ",
    "once in a while":"ときどき",
    "one after another":"次々に",
    "prior to":"～より前に",
    "provided that":"～という条件で",
    "quite a few":"かなり多くの～",
    "regardless of":"～にもかかわらず",
    "to some extent":"ある程度まで",
    "to the point":"的を射た、核心の",
    "when it comes to":"～については、～の話になると",
    "with regard to":"～に関して",
}
day20={
    "adhere to":"～に従う、～に固執する",
    "be entitled to":"～の資格がある",
    "be obliged to do":"～を義務付けられている、～しなければならない",
    "come up with":"～を考え出す",
    "comply with":"（規則に）従う",
    "do away with":"～を廃止する、～を処分する",
    "draw up":"～を作成する、～を立案する",
    "drop in on":"～を訪ねる",
    "end up ～ing":"結局～になる",
    "figure out":"～がわかる、～を解決する",
    "get in touch with":"～と連絡を取る",
    "have nothing to do with":"～と関係がない",
    "have yet to do":"まだ～してない、これから～する必要がある",
    "keep track of":"～の経過を追う、～を追跡する",
    "look after":"～の世話をする、～に気を配る",
    "look into":"～を調べる",
    "make a difference":"違いをもたらす、役に立つ",
    "make it":"間に合う、成功する、都合がつく",
    "make up for":"～を埋め合わせする",
    "mark down":"～を値下げる",
    "pass away":"亡くなる",
    "plug in":"～を電源につなぐ",
    "pull over":"停車させる、路肩に寄せる",
    "put aside":"～脇に置く、～を貯める、～を無視する",
    "rely on":"～を頼る、～を当てにする",
    "report to":"～を下で働く、～に報告義務がある",
    "run errands":"使いに行く",
    "run into":"～に偶然出会う、～に追突する",
    "run out of":"～を使い果たす、～をなくす",
    "see to it that":"～になるように取りはからう",
    "settle down":"～を落ち着かせる、身を落ち着ける、居を定める",
    "sum up":"～を合計する、～を要約する",
    "take ～into account":"～を考慮する、～に気を配る",
    "take advantage of":"～を利用する、～につけこむ",
    "take effect":"効力を生じる、(薬が)効く",
    "take over":"(仕事などを)引き継ぐ、(会社)買収する",
    "turn around":"～を再生させる、再生する、方向転換する",
    "turn down":"～を断る、(音量などを)下げる",
    "turn out to be":"～であることがわかる、～という結果になる",
    "wrap up":"～を終える、厚着をする",
}
